// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_CLONE_PASSWORDVALIDATOR
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_CLONE_PASSWORDVALIDATOR
uint64_t uniffi_locksmith_fn_clone_passwordvalidator(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FREE_PASSWORDVALIDATOR
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FREE_PASSWORDVALIDATOR
void uniffi_locksmith_fn_free_passwordvalidator(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_CONSTRUCTOR_PASSWORDVALIDATOR_NEW
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_CONSTRUCTOR_PASSWORDVALIDATOR_NEW
uint64_t uniffi_locksmith_fn_constructor_passwordvalidator_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_OLD_PASSWORD_POLICY
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_OLD_PASSWORD_POLICY
RustBuffer uniffi_locksmith_fn_method_passwordvalidator_old_password_policy(uint64_t ptr, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_SAY_AFTER
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_SAY_AFTER
uint64_t uniffi_locksmith_fn_method_passwordvalidator_say_after(uint64_t ptr, uint64_t ms, RustBuffer who
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE
RustBuffer uniffi_locksmith_fn_method_passwordvalidator_validate(uint64_t ptr, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORD_MESSAGE_NON_LOCALIZED
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORD_MESSAGE_NON_LOCALIZED
RustBuffer uniffi_locksmith_fn_method_passwordvalidator_validate_password_message_non_localized(uint64_t ptr, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_COUNT_VALID
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_COUNT_VALID
uint64_t uniffi_locksmith_fn_method_passwordvalidator_validate_passwords_count_valid(uint64_t ptr, RustBuffer inputs, uint32_t rounds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_SCORE_REPEATED
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_SCORE_REPEATED
uint64_t uniffi_locksmith_fn_method_passwordvalidator_validate_passwords_score_repeated(uint64_t ptr, RustBuffer inputs, uint32_t rounds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_WITH_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_METHOD_PASSWORDVALIDATOR_VALIDATE_WITH_MESSAGE
RustBuffer uniffi_locksmith_fn_method_passwordvalidator_validate_with_message(uint64_t ptr, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_ADD
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_ADD
uint64_t uniffi_locksmith_fn_func_add(uint64_t a, uint64_t b, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_DIFFERENCE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_DIFFERENCE
uint64_t uniffi_locksmith_fn_func_difference(uint64_t a, uint64_t b, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_LOCALIZED_TEXT
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_LOCALIZED_TEXT
RustBuffer uniffi_locksmith_fn_func_get_localized_text(RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_LOCALIZED_TEXT_WITH_PARAMS
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_LOCALIZED_TEXT_WITH_PARAMS
RustBuffer uniffi_locksmith_fn_func_get_localized_text_with_params(RustBuffer key, RustBuffer params, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_RUST_DEMO_TITLE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_RUST_DEMO_TITLE
RustBuffer uniffi_locksmith_fn_func_get_rust_demo_title(RustBuffer name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_TRANSLATED_TEXT
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_GET_TRANSLATED_TEXT
RustBuffer uniffi_locksmith_fn_func_get_translated_text(RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_INIT_LOCALIZATION
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_INIT_LOCALIZATION
void uniffi_locksmith_fn_func_init_localization(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_INITIALIZE_LOCALIZATION
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_INITIALIZE_LOCALIZATION
void uniffi_locksmith_fn_func_initialize_localization(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_SET_APP_LOCALE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_SET_APP_LOCALE
void uniffi_locksmith_fn_func_set_app_locale(RustBuffer locale, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_SET_GLOBAL_LOCALE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_SET_GLOBAL_LOCALE
void uniffi_locksmith_fn_func_set_global_locale(RustBuffer locale, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_VALIDATE_PASSWORD_LOCALIZED
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_FN_FUNC_VALIDATE_PASSWORD_LOCALIZED
RustBuffer uniffi_locksmith_fn_func_validate_password_localized(RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_ALLOC
RustBuffer ffi_locksmith_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_locksmith_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_FREE
void ffi_locksmith_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUSTBUFFER_RESERVE
RustBuffer ffi_locksmith_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U8
void ffi_locksmith_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U8
void ffi_locksmith_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U8
void ffi_locksmith_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_locksmith_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I8
void ffi_locksmith_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I8
void ffi_locksmith_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I8
void ffi_locksmith_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I8
int8_t ffi_locksmith_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U16
void ffi_locksmith_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U16
void ffi_locksmith_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U16
void ffi_locksmith_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_locksmith_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I16
void ffi_locksmith_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I16
void ffi_locksmith_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I16
void ffi_locksmith_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I16
int16_t ffi_locksmith_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U32
void ffi_locksmith_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U32
void ffi_locksmith_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U32
void ffi_locksmith_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_locksmith_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I32
void ffi_locksmith_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I32
void ffi_locksmith_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I32
void ffi_locksmith_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I32
int32_t ffi_locksmith_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_U64
void ffi_locksmith_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_U64
void ffi_locksmith_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_U64
void ffi_locksmith_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_locksmith_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_I64
void ffi_locksmith_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_I64
void ffi_locksmith_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_I64
void ffi_locksmith_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_I64
int64_t ffi_locksmith_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_F32
void ffi_locksmith_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_F32
void ffi_locksmith_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_F32
void ffi_locksmith_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_F32
float ffi_locksmith_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_F64
void ffi_locksmith_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_F64
void ffi_locksmith_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_F64
void ffi_locksmith_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_F64
double ffi_locksmith_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_locksmith_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_locksmith_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_locksmith_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_locksmith_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_POLL_VOID
void ffi_locksmith_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_CANCEL_VOID
void ffi_locksmith_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_FREE_VOID
void ffi_locksmith_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_RUST_FUTURE_COMPLETE_VOID
void ffi_locksmith_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_ADD
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_ADD
uint16_t uniffi_locksmith_checksum_func_add(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_DIFFERENCE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_DIFFERENCE
uint16_t uniffi_locksmith_checksum_func_difference(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_LOCALIZED_TEXT
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_LOCALIZED_TEXT
uint16_t uniffi_locksmith_checksum_func_get_localized_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_LOCALIZED_TEXT_WITH_PARAMS
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_LOCALIZED_TEXT_WITH_PARAMS
uint16_t uniffi_locksmith_checksum_func_get_localized_text_with_params(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_RUST_DEMO_TITLE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_RUST_DEMO_TITLE
uint16_t uniffi_locksmith_checksum_func_get_rust_demo_title(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_TRANSLATED_TEXT
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_GET_TRANSLATED_TEXT
uint16_t uniffi_locksmith_checksum_func_get_translated_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_INIT_LOCALIZATION
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_INIT_LOCALIZATION
uint16_t uniffi_locksmith_checksum_func_init_localization(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_INITIALIZE_LOCALIZATION
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_INITIALIZE_LOCALIZATION
uint16_t uniffi_locksmith_checksum_func_initialize_localization(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_SET_APP_LOCALE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_SET_APP_LOCALE
uint16_t uniffi_locksmith_checksum_func_set_app_locale(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_SET_GLOBAL_LOCALE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_SET_GLOBAL_LOCALE
uint16_t uniffi_locksmith_checksum_func_set_global_locale(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_VALIDATE_PASSWORD_LOCALIZED
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_FUNC_VALIDATE_PASSWORD_LOCALIZED
uint16_t uniffi_locksmith_checksum_func_validate_password_localized(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_OLD_PASSWORD_POLICY
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_OLD_PASSWORD_POLICY
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_old_password_policy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_SAY_AFTER
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_SAY_AFTER
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_say_after(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_validate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORD_MESSAGE_NON_LOCALIZED
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORD_MESSAGE_NON_LOCALIZED
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_validate_password_message_non_localized(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_COUNT_VALID
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_COUNT_VALID
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_validate_passwords_count_valid(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_SCORE_REPEATED
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_PASSWORDS_SCORE_REPEATED
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_validate_passwords_score_repeated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_WITH_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_METHOD_PASSWORDVALIDATOR_VALIDATE_WITH_MESSAGE
uint16_t uniffi_locksmith_checksum_method_passwordvalidator_validate_with_message(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_CONSTRUCTOR_PASSWORDVALIDATOR_NEW
#define UNIFFI_FFIDEF_UNIFFI_LOCKSMITH_CHECKSUM_CONSTRUCTOR_PASSWORDVALIDATOR_NEW
uint16_t uniffi_locksmith_checksum_constructor_passwordvalidator_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOCKSMITH_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_LOCKSMITH_UNIFFI_CONTRACT_VERSION
uint32_t ffi_locksmith_uniffi_contract_version(void
    
);
#endif

